### ISSUE TITLE
Cannot consume scoped service 'RabbitMQ.Client.IConnectionFactory' from singleton 'Tossit.RabbitMQ.IConnectionWrapper'.

### ISSUE THREAD

**Issue by flower233** [turgayozgur/tossit#16]
发生了 System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot consume scoped service 'RabbitMQ.Client.IConnectionFactory' from singleton 'Tossit.RabbitMQ.IConnectionWrapper'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScoped(ScopedCallSite scopedCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitSingleton(SingletonCallSite singletonCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateCallSite(Type serviceType, IServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Tossit.RabbitMQ.ApplicationBuilderExtensions.UseRabbitMQServer(IApplicationBuilder app, String uri)
   at ElevatorCore.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in E:\Projects\ElevatorCore\ElevatorCore\Startup.cs:line 76

**Comment by turgayozgur** [comment]
Are you sure to you have installed the Tossit.RabbitMq nuget package?

**Comment by flower233** [comment]
when i put in the docker is error, else is normal

**Comment by turgayozgur** [comment]
Version 1.0.1 released. Just use this version.

**Comment by flower233** [comment]
Is Same   v1.0.1
System.InvalidOperationException: 'Cannot consume scoped service 'Tossit.WorkQueue.Job.IJobNameValidator' from singleton 'Tossit.WorkQueue.Worker.IWorkerRegistrar'.'

**Comment by turgayozgur** [comment]
I need to check all singletons. It will be fixed soon.

**Comment by turgayozgur** [comment]
I pushed a new commit about that and published new release 1.0.2 but I couldn't get an exception when I try my samples in a docker container. So, I am not sure that the problem fixed as one hundred percent. Let's try a 1.0.2 version and let me know it fixed or not.

**Comment by flower233** [comment]
System.InvalidOperationException: 'Cannot resolve scoped service 'Tossit.WorkQueue.Worker.IWorkerRegistrar' from root provider.'

**Comment by turgayozgur** [comment]
Could you share your code with me?

**Comment by flower233** [comment]
now i use host.but the same
System.InvalidOperationException:“Cannot resolve scoped service 'Tossit.WorkQueue.Worker.IWorkerRegistrar' from root provider.”

**Comment by turgayozgur** [comment]
Please make sure that you have used `services.AddTossitWorker();` method int the `ConfigureServices(IServiceCollection services)`. If it is okey and still not works, there is an another solution here:

Change:

```csharp
public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .Build();
```

To:

```csharp
public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseDefaultServiceProvider(options => 
            options.ValidateScopes = false)
        .Build();
```
